SELECT TOP (1000) [continent]
      ,[location]
      ,[date]
      ,[population]
      ,[new_vaccinations]
      ,[rollingcountofpeoplevaccination]
  FROM [portfolio project ].[dbo].[percentpeoplevaccinated]
